version: '3.9'

services:
  posgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: fake_payment_provider_app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fake_payment_provider_database
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"